// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpy8CMK2ZA5chXfDS4BpaK0DuVtiedDok',
    appId: '1:518093059785:web:0a56ce2cce0254caefbf18',
    messagingSenderId: '518093059785',
    projectId: 'simplelogin-9538d',
    authDomain: 'simplelogin-9538d.firebaseapp.com',
    storageBucket: 'simplelogin-9538d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhuEdi5weqG3XHbtk3p9aT_9bk3qrGlo',
    appId: '1:518093059785:android:2b5b1c95c2d1e9a5efbf18',
    messagingSenderId: '518093059785',
    projectId: 'simplelogin-9538d',
    storageBucket: 'simplelogin-9538d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpN4CdMYoVW9iFrOKSzt26hv6pkbTi8r8',
    appId: '1:518093059785:ios:62521fdda7a13b94efbf18',
    messagingSenderId: '518093059785',
    projectId: 'simplelogin-9538d',
    storageBucket: 'simplelogin-9538d.appspot.com',
    iosClientId: '518093059785-1octprgkivjvmoa6eidvr320q71pi90m.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpN4CdMYoVW9iFrOKSzt26hv6pkbTi8r8',
    appId: '1:518093059785:ios:62521fdda7a13b94efbf18',
    messagingSenderId: '518093059785',
    projectId: 'simplelogin-9538d',
    storageBucket: 'simplelogin-9538d.appspot.com',
    iosClientId: '518093059785-1octprgkivjvmoa6eidvr320q71pi90m.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );
}
